name: Setup Cache

inputs:
  prefix:
    description: "Cache key prefix"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    #
    # Cache
    #
    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        create-symlink: false
        append-timestamp: false
        key: ${{ inputs.prefix }}-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.prefix }}-${{ runner.os }}-${{ runner.arch }}
        max-size: 1G
        evict-old-files: job
        variant: ${{ runner.os == 'Windows' && 'ccache' || 'ccache' }}

    - name: Configure ccache path
      if: runner.os == 'macOS' || runner.os == 'Linux'
      shell: bash
      run: |
        echo "/usr/lib/ccache" >> $GITHUB_PATH
        echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH
        echo "/opt/homebrew/opt/ccache/libexec" >> $GITHUB_PATH

    # See https://github.com/ccache/ccache/wiki/MS-Visual-Studio
    # The same instructions apply to sccache
    - name: Setup ccache
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        # Find ccache in path and copy it to cl.exe
        $ccache = Get-Command ccache.exe -ErrorAction Stop
        if ($ccache -eq $null) {
          Write-Host "ccache not found in PATH"
          exit 1
        }

        # Copy $ccache to C:\cl.exe
        Copy-Item $ccache.Path C:\cl.exe

        # Set required environment variables for ccache to work with MSVC
        echo "USING_BUILD_CACHE=true" >> $env:GITHUB_ENV
        echo "CLToolExe=C:\cl.exe" >> $env:GITHUB_ENV
        echo "CLToolPath=C:\" >> $env:GITHUB_ENV
