name: macOS FQDN
description: Ensures the macOS runner has a valid Fully Qualified Domain Name (FQDN) by checking and fixing its hostname configuration.
runs:
  using: "composite"
  steps:
    # The macOS FQDN can be misconfigured on GitHub-hosted runners,
    # causing issues with some tests that expect a valid FQDN.
    # See https://github.com/actions/runner-images/issues/12562
    #
    # Example from a runner that is good:
    # > scutil --get ComputerName
    # iad20-fj925-81b5ba22-7890-42f2-92e2-f0dbf5ebb8ed-1E029398D518
    # > scutil --get LocalHostName
    # iad20-fj925-81b5ba22-7890-42f2-92e2-f0dbf5ebb8ed-1E029398D518
    # > scutil --get HostName
    # iad20-fj925-81b5ba22-7890-42f2-92e2-f0dbf5ebb8ed-1E029398D518.local

    - name: Check and fix FQDN
      shell: bash
      run: |
        FQDN=$(hostname -f)
        if ! grep -qF "$FQDN" /etc/hosts; then
            echo "FQDN $FQDN not found in /etc/hosts"

            # Find the entry in /etc/hosts that corresponds to what the hostname should be.
            # It's the one that ends in ".local" and is not "localhost" or "broadcasthost".
            ENTRY=$(grep '\.local' /etc/hosts | grep -v 'localhost' | grep -v 'broadcasthost' | grep -v '^#' | head -1 || true)
            if [ -n "$ENTRY" ]; then
              HOSTNAME=$(echo "$ENTRY" | awk '{print $2}')
              COMPUTER_NAME="${FQDN%%.*}"
              echo "Setting hostname/fqdn from /etc/hosts: $HOSTNAME / $FQDN"

              sudo scutil --set ComputerName "$COMPUTER_NAME" # keep domain part for ComputerName
              sudo scutil --set LocalHostName "$COMPUTER_NAME" # strip domain part for LocalHostName
              sudo scutil --set HostName "$HOSTNAME" # strip domain part for HostName

              sudo dscacheutil -flushcache
            else
              echo "No suitable entry found in /etc/hosts."
            fi
          fi
