% Script:
% Generate Ice for MATLAB documentation using m2docgen
% See https://github.com/nilsBoeAc/m2docgen/blob/bf146a78def51c7913f4a7df176b76037a77c1d2/release/help/run_m2docgen_example.m

% cd(fileparts(which(mfilename)));
cPath = fileparts(which(mfilename));
mF = fileparts(cPath);
mF = fullfile(mF, 'src');
oF = fullfile(mF, 'm2docgen_documentation');

% opts = struct(  'toolboxName',      "Ice", ...
%                 'delOld',           true, ...
%                 'mFolder',          [mF], ...
%                 'outputFolder',     [oF], ...
%                 'excludeFolder',	  ["m2docgen_documentation"], ...
%                 'excludeFile',      [""], ...
%                 'htmlMetaFolder',   "resources", ...
%                 'htmlTemplate',     "m2doc-standard", ...
%                 'startPage',        [""], ...
%                 'toc',              [], ...
%                 'verbose',          true);

opts = struct('toolboxName', "Ice", ...
              'delOld', true, ...
              'mFolder', [mF], ...
              'outputFolder', [oF], ...
              'excludeFile', [""], ...
              'excludeFolder', ["m2docgen_documentation"], ...
              'htmlMetaFolder', "resources", ...
              'htmlTemplate',     "m2doc-standard", ...
              'startPage',        [""], ...
              'toc',              [], ...
              'verbose', true);

res = m2docgen(opts);
